# Generated by Django 2.2.9 on 2022-09-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goalID', models.BigAutoField(primary_key=True, serialize=False)),
                ('goalDesc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapItems',
            fields=[
                ('itemID', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemDesc', models.CharField(max_length=300)),
                ('completionRate', models.FloatField()),
                ('deadline', models.DateTimeField()),
                ('assGoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roadmap.Goals')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskID', models.BigAutoField(primary_key=True, serialize=False)),
                ('taskDesc', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('assRoadmapItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roadmap.RoadmapItems')),
            ],
        ),
    ]
